package testException;

public class Main {

	public static void main(String[] args) {
	
		int x = 0;
		int y = 5/x;
		try {
			System.out.println(y);
		}
		catch (ArithmeticException e) {
			System.out.println("Exception : Division par zero ");
		}
		System.out.println("Fin de calcul");
			


	}

}
