package testException;

public class Main {

	public static void main(String[] args) {
	
		int x = 0;
		int y = 5;
		try {
			System.out.println(y/x);
		}
		catch (ArithmeticException e) {
			System.out.println(e);
		}
		System.out.println("Fin de calcul");
			


	}

}
